### ISSUE TITLE
application issue

### ISSUE THREAD

**Issue by prashantbasvat** [rpricken/cc3100-linux#1]
i ported wifi drivers and app on embedded linux systems,but when i am running application my app gets blocked to get some response ffrom cc3100 device.this happened after getting sync response.
how to resolve this.

**Comment by rpricken** [comment]
I was facing some simular issues with my rPi. The solution was to disable the os porting in user.h.
Just delete the define "#define SL_PLATFORM_MULTI_THREADED" (plattform/linux/user.h ~L 714).

**Comment by prashantbasvat** [comment]
can u give m urs email-id or skype-id for technical chat as i am porting the cc3100 on tiny6410 friendly arm board.

**Comment by prashantbasvat** [comment]
can u give m urs email-id or skype-id for technical chat as i am porting the cc3100 on tiny6410 friendly arm board.

**Comment by rpricken** [comment]
github[at]pricken.info

**Comment by prashantbasvat** [comment]
other than github

**Comment by rpricken** [comment]
it is a normal email adress...

**Comment by prashantbasvat** [comment]
no skype-id or gtalk id

**Comment by prashantbasvat** [comment]
i execute tcp_socket demo,but i am getting following error message
" Failed to establish connection w/ an AP ".
 NOTE : i have crerated a one hotspot wifi connection and i have given their credentials.
what i found that there are call back routine in main.c like following
 SimpleLinkWlanEventHandler() these is nt getting executed, by putting fprintf() inside that function
,because of which it keeps checking for ip_acquired event
so how to get rid of these

**Comment by prashantbasvat** [comment]
hello rpricken sir how to handle this issue as i m newbie in wifi arena

**Comment by rpricken** [comment]
The others examples, spi_debug_tool and getting_started_with_wlan_ap are working properly?
If so, did you set your Wi-Fi preferences like SSID-Name, security-type etc. in sl_common.h correctly?

**Comment by prashantbasvat** [comment]
yes i setup all configuration parameters in s;_common.h.and wlan_ap also facing same issue.
in order to check whether SimpleLinkWlanEventHandler() executing what i did is i placed fprintf() in that function.after running app,i found that its nt displaying that function message,maybe event is coming but app not able to handle it????

**Comment by rpricken** [comment]
So the spi_debug_tool runs successfull? If so the basic communication between cc3100 and your tiny6410 works.
Did you try to disable the "#define SL_PLATFORM_MULTI_THREADED"?

**Comment by prashantbasvat** [comment]
yes spi_debug_tool works fine,and i comment SL_PLATFORM_MULTI_THREADED defines.i want to know bit pattern when ip acquired event send by cc3100 to host i.e. event bit pattern.as my wlaneventhandlers are not executing as they only responsible for setting up status flag

**Comment by rpricken** [comment]
Try a static IP, like in this example?
http://processors.wiki.ti.com/index.php/CC31xx_IP_Configuration_Application
