### ISSUE TITLE
 application issue

### ISSUE THREAD

**Issue by Aashish25** [rpricken/cc3100-linux#2]
@rpricken can you please give detail explanation of following statements,
add am335x-bone-cc3100-spi.dtsi to /linux/arch/arm/boot/dts
include the file in am335x-bone.dts (under #include "am335x-can1.dtsi")

```
#include "am335x-bone-cc3100-spi.dtsi"
```

compile your kernel
place am335x-bone.dtb in /boot/dtbs/

after a reboot you can insert the kernel module

```
insmod cc3100-spi.ko
```

  in your repository.

**Comment by Aashish25** [comment]
After following all of above instructions when i tried to compile kernel module i got many errors, some of them are listed below
In file included from /usr/src/linux-3.8.13-bone70/include/asm/bitops.h:23:0,
                 from /usr/src/linux-3.8.13-bone70/include/linux/bitops.h:22,
                 from /usr/src/linux-3.8.13-bone70/include/linux/kernel.h:10,
                 from /usr/src/linux-3.8.13-bone70/include/linux/cache.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/time.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/stat.h:18,
                 from /usr/src/linux-3.8.13-bone70/include/linux/module.h:10,
                 from cc3100-spi.c:15:
/usr/src/linux-3.8.13-bone70/include/asm-generic/bitops/**ffs.h:12:24: error: expected '=', ',', ';', 'asm' or '__attribute**' before 'unsigned'
In file included from /usr/src/linux-3.8.13-bone70/include/asm/bitops.h:25:0,
                 from /usr/src/linux-3.8.13-bone70/include/linux/bitops.h:22,
                 from /usr/src/linux-3.8.13-bone70/include/linux/kernel.h:10,
                 from /usr/src/linux-3.8.13-bone70/include/linux/cache.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/time.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/stat.h:18,
                 from /usr/src/linux-3.8.13-bone70/include/linux/module.h:10,
                 from cc3100-spi.c:15:
/usr/src/linux-3.8.13-bone70/include/asm-generic/bitops/fls.h:12:24: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'int'
In file included from /usr/src/linux-3.8.13-bone70/include/asm/bitops.h:26:0,
                 from /usr/src/linux-3.8.13-bone70/include/linux/bitops.h:22,
                 from /usr/src/linux-3.8.13-bone70/include/linux/kernel.h:10,
                 from /usr/src/linux-3.8.13-bone70/include/linux/cache.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/time.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/stat.h:18,
                 from /usr/src/linux-3.8.13-bone70/include/linux/module.h:10,
                 from cc3100-spi.c:15:
/usr/src/linux-3.8.13-bone70/include/asm-generic/bitops/**fls.h:12:24: error: expected '=', ',', ';', 'asm' or '__attribute**' before 'unsigned'
In file included from /usr/src/linux-3.8.13-bone70/include/asm/bitops.h:27:0,
                 from /usr/src/linux-3.8.13-bone70/include/linux/bitops.h:22,
                 from /usr/src/linux-3.8.13-bone70/include/linux/kernel.h:10,
                 from /usr/src/linux-3.8.13-bone70/include/linux/cache.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/time.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/stat.h:18,
                 from /usr/src/linux-3.8.13-bone70/include/linux/module.h:10,
                 from cc3100-spi.c:15:
/usr/src/linux-3.8.13-bone70/include/asm-generic/bitops/fls64.h:18:24: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'int'
In file included from /usr/src/linux-3.8.13-bone70/include/linux/kernel.h:13:0,
                 from /usr/src/linux-3.8.13-bone70/include/linux/cache.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/time.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/stat.h:18,
                 from /usr/src/linux-3.8.13-bone70/include/linux/module.h:10,
                 from cc3100-spi.c:15:
In file included from /usr/src/linux-3.8.13-bone70/include/linux/dynamic_debug.h:100:0,
                 from /usr/src/linux-3.8.13-bone70/include/linux/kernel.h:14,
                 from /usr/src/linux-3.8.13-bone70/include/linux/cache.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/time.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/stat.h:18,
                 from /usr/src/linux-3.8.13-bone70/include/linux/module.h:10,
                 from cc3100-spi.c:15:
/usr/src/linux-3.8.13-bone70/include/linux/string.h:61:28: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'skip_spaces'
/usr/src/linux-3.8.13-bone70/include/linux/string.h:65:28: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'char'
In file included from /usr/src/linux-3.8.13-bone70/include/linux/kernel.h:16:0,
                 from /usr/src/linux-3.8.13-bone70/include/linux/cache.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/time.h:4,
                 from /usr/src/linux-3.8.13-bone70/include/linux/stat.h:18,
                 from /usr/src/linux-3.8.13-bone70/include/linux/module.h:10,
                 from cc3100-spi.c:15:
/usr/src/linux-3.8.13-bone70/include/uapi/linux/kernel.h:4:27: fatal error: linux/sysinfo.h: No such file or directory
compilation terminated.
Could you please tell me what might be going wrong? Or else please tell me from staring how to do it in detail.....it will be very much helpful.
Thanks,
Aashish

**Comment by rpricken** [comment]
Can you compile the kernel without including the am335x-bone-cc3100-spi.dtsi file?
If not, please follow these instructions how to update/compile a kernel for a beaglebone:
http://elinux.org/Building_BBB_Kernel
After successfully updating/compiling the kernel try to include the dtsi file.

**Comment by jeysurier** [comment]
rpricken,
thanks for all these info. I followed this instruction and created the kernel module for my Beaglebone Black. I booted the system, did the "insmod cc3100-spi.ko." When I ran the application, I am getting the following error: 
                              "Can't open device file: /dev/cc3100-spi"

But this file exists. Any idea, what could I be doing wrong?
Thanks
Jey
