### ISSUE TITLE
Getting Error: "Can't open device file: /dev/cc3100-spi"

### ISSUE THREAD

**Issue by jeysurier** [rpricken/cc3100-linux#3]
rpricken,
thanks for all the detailed info. I wanted to run the wlanap application, and followed the instructions. I loaded the "insmod cc3100-spi.ko", and started the ./wlanap, but getting the following error:
          "Can't open device file: /dev/cc3100-spi"

But when I checked for this file, it exists.
           ubuntu@arm:/jey$ ls -al /dev/cc3100-spi
            crw------- 1 root root 10, 56 Jun  9 13:48 /dev/cc3100-spi

Any idea, what could I be doing wrong?
thx
Jey

**Comment by rpricken** [comment]
Did you try to start ./wlanap as root?
And what stands in your kernel log after running "insmod cc3100.ko"? ("dmesg | tail")

**Comment by jeysurier** [comment]
rPricken, thanks. I think I wasn't running it as root, I will try and let you know, once I am back in my lab a week from now again. Thanks.
Jey
