### ISSUE TITLE
Reference to non-existent node or label "spi0_pins"

### ISSUE THREAD

**Issue by dadas190** [rpricken/cc3100-linux#5]
Hello there, I am using Beaglebone Black and tried to compile kernel 4.1 (https://github.com/beagleboard/linux) with modified am335x-bone.dts to include am335x-bone-cc3100-spi.dtsi - this gives the following error:

DTC     arch/arm/boot/dts/am335x-boneblack.dtb
ERROR (phandle_references): Reference to non-existent node or label "spi0_pins"

Should I include the file in another .dts, for example am335x-boneblack-spi0.dts?

Thanks in advance

**Comment by rpricken** [comment]
On which line do you try to include "am335x-bone-cc3100-spi.dtsi"?
Try it below "#include "am33xx-overlay-edma-fix.dtsi""

**Comment by dadas190** [comment]
I put it right there, didn't work

EDIT: I will try old 3.14 kernel that is confirmed working

EDIT2: 3.14 compiled ok but spi debug test hangs after "device enable passed"

**Comment by rpricken** [comment]
Okay, so probably they changed something in the device tree in the newer kernel version and SPI0 is not initialized on default.

Your second problem could be caused by different issues:
1) Is everything connected to the right ports?
2) Can you measure a high signal on SPI_CS line after executing the spi debug test program?
3) Can you measure a signal on SPI Clock line?

**Comment by dadas190** [comment]
1) I have tried reconnecting it many times, always double checking everything, so this should be OK

2) and 3) - I don't have required tools, but can you at least verify procedure I used to compile the kernel?

I am using this source: https://github.com/beagleboard/linux/tree/3.14

First i copy the file   am335x-bone-cc3100-spi.dtsi to arch/arm/boot/dts
Then i include it under #include "am335x-can1.dtsi" in both files am335x-bone.dts and am335x-boneblack.dts (just to be sure)

I also uncomment #include "am335x-bone-spi0-spidev.dtsi" in both files, so spi0 should be enabled

Then i compile kernel, dtbs and modules, install them, and then i compile the cc3100-spi.ko.

When BBB boots up, i insert the module and try spi debug tool - stops after device enable passed

I appreciate your work, thanks for help

**Comment by rpricken** [comment]
What says your kernel log, after inserting the kernel module?
dmesg | tail

**Comment by dadas190** [comment]
Nothing related to the module, however i have noticed that when i boot with modified dts, /dev/spidev1.0 disappears and only /dev/spidev1.1 is visible, is this ok? I have no idea what could be wrong

**Comment by rpricken** [comment]
But the cc3100-spi shows up in /dev/?

Another idea: try to set the max clocking speed to 20 Mhz:
line 183: spi->max_speed_hz = 20000000;

I never tested the cc3100 with a beaglebone black, so I can't promise that it is going to work...

**Comment by dadas190** [comment]
I have got it to work, the GPIO pins were issue, for some reason they didn't really change values when they should, I have changed them to 67 and 68 (P8_8 and P8_10) by modifiing am335x-bone-cc3100-spi.dts and everything works now :D Thanks for all your support and excellent driver

**Comment by rpricken** [comment]
Perfect, I'm really happy that it's working now.

**Comment by dadas190** [comment]
Hello I am back, run into one more problem - I have created TCP socket via CC3100 and tried to receive a file (small jpg, 6kb size) - after about 1kb of sent data it hangs. I have tried to set smaller SPI frequency but didnt help. I have also tried to disable SL_PLATFORM_MULTITHREADED, but after i did that, it stopped even before a client connected.

Do you have any other ideas?

Same code worked on windows with no problems (via emuboard)
